### ISSUE TITLE
gigabyte flashing

### ISSUE THREAD

**Issue by fe3r0fN0thn1g** [ekknod/smm#2]
Does anyone know how to flash the bios on gigabyte/aorus mainboards i tryed q-flash from inside the bios and i tryed the software both just giving me errors. https://gyazo.com/9b7edb8195dfe44bc8b0a31c47f68398

**Comment by kaisersoju** [comment]
Many official flashing utilities will verify with some form of integrity check on the new firmware as protection against bricking your mobo. Try another utility that's compatible with your gigabyte mobo. Good luck.

**Comment by fe3r0fN0thn1g** [comment]
Looks like faceit did a patch that when you put your pc to sleep now that it will go all the way to sleep with closing all open programs, putting your pc to sleep without faceit driver running works just fine.
